[build]
  publish = "dist/spa"
  command = "quasar build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com 'unsafe-inline';
      connect-src 'self' https://www.google-analytics.com;
      img-src 'self' https://www.google-analytics.com data:;
      style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;
      font-src 'self' https://cdnjs.cloudflare.com;
    '''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
